version:  "2"

services:
  elasticsearch:
    image: dock-server.duckdns.org/elasticsearch:latest
    build: elasticsearch/
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: dock-server.duckdns.org/logstash:latest
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5006:5006"
    links:
      - elasticsearch
  kibana:
    image: dock-server.duckdns.org/kibana:latest
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
